### PR TITLE
Manila actions

### PR DESCRIPTION
**Pull request by Carthaca**
clean replacement of #212 after renaming to "shared file system"

@gildub fyi

### CODE REVIEW

**Comment by gildub** [comment]
@Carthaca, 

Could you please rebase? That would help the review since lot's of file have been merged. Thank you

**Comment by Carthaca** [comment]
I will wait until https://github.com/fog/fog-openstack/pull/217 has been merged

**Comment by gildub** [comment]
@Carthaca, please rebase.

**Comment by Carthaca** [comment]
done

**Comment by gildub** [comment]
@Carthaca,

Sorry for late reply, I had several software/hardware upgrade in the pipe!
Anyway, that's great and looks good.
Although I think it would be better to have the microversion commit in a separate PR.
Would you mind split?

**Comment by seanhandley** [comment]
Agreed on the Microversion support being in a separate PR.

Awesome work adding that in - I was just looking at tackling that for my pending Magnum integration in #231 👍

**Comment by Carthaca** [comment]
Now it was me, who was absent, sorry - I cherry-picked the microversion commit to https://github.com/fog/fog-openstack/pull/242

**Comment by gildub** [comment]
@Carthaca, thanks for the microversion effort. Could you please rebase so we can merge this one too 👍

**Comment by Carthaca** [comment]
thanks for reviewing :) I suggest to use the 'squash and merge' strategy here

**Comment by gildub** [comment]
@Carthaca, unfortunately I believe you have to split from the microversion version code that has been merged because we don't have the luxury of interactive rebase when we hit the merge button.

**Comment by Carthaca** [comment]
Hi @gildub, it is already rebased - and what's wrong with using the github luxury of squashing these two commits (because https://github.com/fog/fog-openstack/pull/218/commits/05326c74bdb7b90dd791d02f30e76aec07aae08e is really not worth being a single one)?

**Comment by gildub** [comment]
Hi @Carthaca, 

Sorry, you're right, I just realized github actually has the option :)
That said doing an interactive rebase before always make the review easier. Anyway that's fine for this one which look very good to me.

Thank you.

**Pull request merged**
