### PR TITLE
[WIP] Add uri.path in openstack get_version method

### LINKED ISSUE #362: [openstack][pike] Compute[:openstack].servers doesn't work
Trying to connect locally deployed openstack (pike) with fog 1.42.0.

Firstly, curl connection works well with the command: https://hastebin.com/fihojuqize.scala

With this in mind, i've created fog credentials file: https://hastebin.com/hexanixucu.scala and run

fog openstack
Compute[:openstack].servers

This leads to an error like [full text here](https://hastebin.com/bucugizipi.php):

```
  :status        => 302
  :status_line   => "HTTP/1.1 302 Found\r\n"

    from /var/lib/gems/2.3.0/gems/excon-0.60.0/lib/excon/middlewares/expects.rb:7:in `response_call'
    from /var/lib/gems/2.3.0/gems/excon-0.60.0/lib/excon/middlewares/response_parser.rb:9:in `response_call'
    from /var/lib/gems/2.3.0/gems/excon-0.60.0/lib/excon/connection.rb:414:in `response'
    from /var/lib/gems/2.3.0/gems/excon-0.60.0/lib/excon/connection.rb:263:in `request'
    from /var/lib/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/core/connection.rb:81:in `request'
    from /var/lib/gems/2.3.0/gems/fog-openstack-0.1.23/lib/fog/openstack.rb:610:in `get_version'
    from /var/lib/gems/2.3.0/gems/fog-openstack-0.1.23/lib/fog/openstack.rb:583:in `get_supported_microversion'
    from /var/lib/gems/2.3.0/gems/fog-openstack-0.1.23/lib/fog/openstack/core.rb:122:in `set_microversion'
    from /var/lib/gems/2.3.0/gems/fog-openstack-0.1.23/lib/fog/openstack/core.rb:212:in `authenticate'
    from /var/lib/gems/2.3.0/gems/fog-openstack-0.1.23/lib/fog/compute/openstack.rb:397:in `initialize'
    from /var/lib/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:115:in `new'
    from /var/lib/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:115:in `new'
    from /var/lib/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/core/services_mixin.rb:16:in `new'
    from /var/lib/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/compute.rb:54:in `new'
    from /var/lib/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/core/services_mixin.rb:4:in `[]'
    from (irb):1:in `<top (required)>'
    from /var/lib/gems/2.3.0/gems/fog-1.42.0/bin/fog:76:in `block in <top (required)>'
    from /var/lib/gems/2.3.0/gems/fog-1.42.0/bin/fog:76:in `catch'
    from /var/lib/gems/2.3.0/gems/fog-1.42.0/bin/fog:76:in `<top (required)>'
    from /usr/local/bin/fog:23:in `load'
    from /usr/local/bin/fog:23:in `<main>
```
First request to "/identity/v3/auth/tokens" was complete, but overall result is bad..

Worth to be mentioned - i've cntlm proxy configured.

### PR DESCRIPTION
**Pull request by aibondarenko**
Based on discussion from the thread below
i hope it fixes #362

### CODE REVIEW

**Comment by gildub** [comment]
@aibondarenko, please remove the "Work in Progress" [WIP] from the title when the tests are green. Thanks

**Comment by TommyLike** [comment]
It's not true for some of the service endpoints, please take a look:

```
+----------------------------------+-----------+--------------+----------------+---------+-----------+----------------------------------------------+
| ID                               | Region    | Service Name | Service Type   | Enabled | Interface | URL                                          |
+----------------------------------+-----------+--------------+----------------+---------+-----------+----------------------------------------------+
| 1fa828c18c8046c88685d417ed8691d8 | RegionOne | nova         | compute        | True    | public    | http://10.0.0.52/compute/v2.1                |
| 24a75a4b31bf49c09e1f4477b90afbfa | RegionOne | swift        | object-store   | True    | public    | http://10.0.0.52:8080/v1/AUTH_$(project_id)s |
| 26a15beded274d60a45f869845852671 | RegionOne | swift        | object-store   | True    | admin     | http://10.0.0.52:8080                        |
| 2c8884052f8747e49d9e8430af25e520 | RegionOne | neutron      | network        | True    | public    | http://10.0.0.52:9696/                       |
| 341f98ee880c4d0ca5f4487581cd8007 | RegionOne | placement    | placement      | True    | public    | http://10.0.0.52/placement                   |
| 46aacf5ffa214967b829be4bfe543a2c | RegionOne | nova_legacy  | compute_legacy | True    | public    | http://10.0.0.52/compute/v2/$(project_id)s   |
| 58683fc65109404e963f219fcfcda4c8 | RegionOne | cinder       | block-storage  | True    | public    | http://10.0.0.52/volume/                     |
| 666ca1b09afd498b8291f5740be88004 | RegionOne | cinderv3     | volumev3       | True    | public    | http://10.0.0.52/volume/v3/$(project_id)s    |
| 7a3a956487944b60ad6e5de55db137a6 | RegionOne | keystone     | identity       | True    | public    | http://10.0.0.52/identity                    |
| 8a0831734ed444dba360b5ab02312a7b | RegionOne | cinderv2     | volumev2       | True    | public    | http://10.0.0.52/volume/v2/$(project_id)s    |
| b986bd7780f943049ab867a8734328b7 | RegionOne | keystone     | identity       | True    | admin     | http://10.0.0.52/identity                    |
| bbfb801b6436497e96825288f2fbb500 | RegionOne | glance       | image          | True    | public    | http://10.0.0.52/image                       |
| d834a258b4784082bc89e18eed08c6a1 | RegionOne | cinder       | volume         | True    | public    | http://10.0.0.52/volume/v1/$(project_id)s    |
+----------------------------------+-----------+--------------+----------------+---------+-----------+----------------------------------------------+
```

We'd either get a version list or a single version via the ``get_version`` method:)

**Comment by TommyLike** [comment]
I am wondering if we can just use the first segment and ignore the rest.
```
connection = Fog::Core::Connection.new("#{uri.scheme}://#{uri.host}:#{uri.port}/#{uri.path.split('/').reject!(&:empty?)[0]}/", false, connection_options)
```

**Comment by gildub** [comment]
@TommyLike,

I got confused too.

A registered endpoint such as '/compute/v2.1' as seen in devstack, seems like special case and I would add a bad endpoint. I can confirm that by just doing a request against '/compute':
```bash
$ curl -s http://192.168.1.8/compute
{"versions": [{"status": "SUPPORTED", "updated": "2011-01-21T11:33:21Z", "links": [{"href": "http://192.168.1.8/compute/v2/", "rel": "self"}], "min_version": "", "version": "", "id": "v2.0"}, {"status": "CURRENT", "updated": "2013-07-23T11:33:21Z", "links": [{"href": "http://192.168.1.8/compute/v2.1/", "rel": "self"}], "min_version": "2.1", "version": "2.63", "id": "v2.1"}]}
```  

Conversely hitting  '/compute/v2.1' which requires authentication shows is not a service discovery not only because it requires authentication but also returns the current version.

**Comment by gildub** [comment]
@TommyLike, BTW thanks for helping.

**Comment by gildub** [comment]
Closing as it's inactive as we needed the tests to be fixed, it has been replaced by #408.

**Pull request closed without merging**
