### PR TITLE
add snapshot_action to cinder

### PR DESCRIPTION
**Pull request by Carthaca**
same like on volumes one can perform certain actions on cinder snapshots

### CODE REVIEW

**Comment by gildub** [comment]
Looks good. 
What about the Mock? Look, I'm not a big fan as I'd like to see them being separated from the real code meanwhile until that happens, don't we we have to stay consistent ?

**Comment by gildub** [comment]
Actually that reminded me to reactivate https://github.com/fog/fog-openstack/pull/223

**Comment by Carthaca** [comment]
It's the minimal method on which you could build something on top like [extend volume](https://github.com/fog/fog-openstack/blob/master/lib/fog/volume/openstack/requests/extend_volume.rb) (which should be refactored to actually use the action method btw)

I fear the `snapshot_action` method itself would be hard to mock, because it is too flexible.
Same like with the [action](https://github.com/fog/fog-openstack/blob/master/lib/fog/volume/openstack/requests/action.rb) method, I would just like to skip this

**Comment by gildub** [comment]
@Carthaca,

Sorry the head in the handle bar, UI stuff is *way* too consuming, anyway I understand the mock would be mockery anyway ;)

**Pull request merged**
