### PR TITLE
Identity API fixes

### PR DESCRIPTION
**Pull request by dhague**
version path fix
prefer project ID over project name
fix caching typo
update VCR recordings & default values

### CODE REVIEW

**Comment by gildub** [comment]
Look good

Ok, re waiting upon #82 and rebase after it has been merged.

One more hound to fix: replacing simple quotes by double quotes. I use to do the same but single ones seems out of trend now, well according to Rubocop!

**Comment by dhague** [comment]
The single quotes thing is annoying - RubyMine suggests using single quotes where there is no interpolation, which seems to be better style to me. I will fix and push an update rebased on #82 once it's merged.

**Comment by gildub** [comment]
Yeah I agree with RubyMine, that's what I been doing to, Grrr!
Thanks

**Comment by seanhandley** [comment]
It used to be that strings with double quotes were slower because the interpreter needed to check for interpolation. As far as I know that's no longer the case so it really doesn't matter from a technical perspective.

Since it makes no real difference, I can see the argument for double quotes all the way through the codebase but frankly it's bikeshedding at best and really doesn't matter 😄

**Comment by gildub** [comment]
@seanhandley, thanks for sharing this interesting little story.

**Pull request merged**
