### PR TITLE
Bump ruby, fog-core versions; Each not each_pair

### PR DESCRIPTION
**Pull request by gildub**
Bumps Ruby minimal version is 2.2.0
Bumps Fog-core 1.45.0 (for now, until [1] is addressed)
Updates .travis and .zuul 
Removes .ruby-version file
Overloads `reload` method from fog-core model because changed behaviour since fog-core 1.45.0
Uses Minitest `assert_nil` to avoid deprecation 

[1] https://github.com/fog/fog-core/issues/236

### CODE REVIEW

**Comment by gildub** [comment]
@mrhillsman, you might be interested by the spec jobs failing.

**Comment by aufi** [comment]
I haven't tested it locally, but changes looks good to me :+1:

**Comment by gildub** [comment]
@mdarby, could you please review?

**Comment by plribeiro3000** [comment]
@gildub This look ok. Could you just bump to `fog-core` `1.45.0` instead?

I pinpointed the issue you mentioned to a commit on the `2.x` series. This would allow you to move on with this and give us some time to investigate the real issue.

Other than that LGTM!

**Comment by gildub** [comment]
@plribeiro3000, you're right, I'll reverse to fog-core 1.45 and remove the overloading.

**Comment by gildub** [comment]
@plribeiro3000, please re-review and merge if happy. Thanks!

**Comment by plribeiro3000** [comment]
👍

**Pull request merged**
