### PR TITLE
Skip tests that make assumptions about the FS.

### PR DESCRIPTION
**Pull request by timuralp**
There is no reasonable way to run tests that use resources with a
hardcoded assumption about where the resource resides. Skip these
tests, unless the directory structure is setup for them to run
successfully (should be the case on Travis and in a docker container).

### CODE REVIEW

**Comment by timuralp** [comment]
Should work around the issue mentioned in #350.

**Comment by gildub** [comment]
@timuralp the workaround is not needed anymore since https://github.com/fog/fog-openstack/pull/364. Thanks

**Comment by timuralp** [comment]
@gildub Can you please read the comment on your PR before closing others?! You waited a total of 30 minutes before merging it and ignored the open issue!

**Comment by gildub** [comment]
@timuralp, as I mentioned in the related issue, I worked on the PR before updating the Issue. Again I'm sorry about the confusion. Meanwhile I don't understand why do we need this one, skipping the test is not needed as there are now green. Of course as you said it might need more coverage.

**Comment by timuralp** [comment]
Merging this following the comments on #350. The PR reverts the reduced test coverage changes and opts to skip the tests, unless running in an environment where the source tree is placed at the expected location. There are ways to improve these tests, but for now we shouldn't sacrifice the test coverage to fix an unknown fog fork that fails to run the tests.

**Pull request merged**
