### PR TITLE
return network in mock data in stead of creating a new one

### PR DESCRIPTION
**Pull request by zhitongLBN**
Pull request from: https://github.com/fog/fog/pull/3846

### CODE REVIEW

**Comment by zhitongLBN** [comment]
@Ladas please merge this PR as rubocop don't cry anymore ;-P

**Comment by Ladas** [comment]
@zhitongLBN Could you please fix the hash aligning, so it is more readable? I see that the test data already contain one network, maybe we don't need to add another one? Or are the tests dependent on those exact values?

**Comment by zhitongLBN** [comment]
@Ladas I heard from @geemus that he has some stuff with that second network he use to get, so i decided to put those 2 networks in the mock data, if you don't really want them, just let me know, and i will remove them

**Comment by Ladas** [comment]
@zhitongLBN ah, I guess it's ok to stay if it's needed. I just wondered why it's there :-) So please just align the hashes, so it's nicely readable and I am ready to merge. :-)

**Comment by Ladas** [comment]
@zhitongLBN hound still complains, but it's ok now, I'll merge once tests are green

**Comment by zhitongLBN** [comment]
I've just reduced the nb of commit, it will be green normally :)

**Comment by Ladas** [comment]
@zhitongLBN awesome, thank you :-)

**Pull request merged**
