### PR TITLE
adding monitoring (monasca) service with tests

### PR DESCRIPTION
**Pull request by auhlig**
As described in #141 this is the initial implementation which will add the monitoring (monasca) service to fog-openstack.
Comes with tests.

Let me know what you think.
@dhague

### CODE REVIEW

**Comment by seanhandley** [comment]
Excellent - thanks @auhlig.

I know it's dull but would you tackle the styling issue reported by hound-ci? We'll review the content itself soon.

**Comment by auhlig** [comment]
@seanhandley Sure. I'm already on it.

**Comment by auhlig** [comment]
After just changing what hound complained about last time it seems even unhappier now. I'm on it ...

**Comment by dhague** [comment]
woohoo!

**Pull request merged**
