### PR TITLE
Add events to metering

### PR DESCRIPTION
**Pull request by tzumainn**

### CODE REVIEW

**Comment by jjasghar** [comment]
Can you add some documentation around this please?

**Comment by tzumainn** [comment]
Sure - in-line, or is there another place for docs I may have missed... ?

**Comment by jjasghar** [comment]
Great question. Probably should start something up. I suggest we create a `docs/` directory off the root, and then maybe start a file called `metering.md`?

We can make md's per each model, which can help out the general understanding of what this gem supports/can do.

**Comment by tzumainn** [comment]
Sounds good!  Is there an existing doc with a format you like, or should I just make one up?

**Comment by jjasghar** [comment]
Yeah go a head and make it up, we can work with whatever you start with and mold it as time progresses.

Something I've hated about fog in general is the lack of documentation, so I'm excited to see that we are making a positive change on our little plugin gem here to help our future selves :metal:.

**Comment by Ladas** [comment]
@tzumainn there is already docs dir with examples https://github.com/fog/fog-openstack/blob/master/lib/fog/openstack/docs/compute.md

@jjasghar it's not wildly used, so maybe just continuing with this and then moving it?

**Comment by jjasghar** [comment]
@ladas oh wow totally missed that. We should probably move that to a better location or reference it in the readme. 

@tzumainn go ahead a use that format for now as we figure out what we want to do. Thanks!

**Comment by tzumainn** [comment]
Ah, cool!  I'll just add to that existing directory and let others figure out if the directory needs to be moved : )

**Comment by tzumainn** [comment]
Added a short doc.  It's far more succinct than the others, primarily because it seemed as if the other docs had a lot of duplicate information.  Let me know if you'd like changes!

**Comment by jjasghar** [comment]
@tzumainn that's PERFECT thank you. I'm good with this merge now. :+1: 

@Ladas any thoughts?

**Comment by seanhandley** [comment]
Nice one @tzumainn :+1:

**Comment by aufi** [comment]
Looks good!

**Pull request merged**
