### PR TITLE
Drop Ruby<2 support

### PR DESCRIPTION
**Pull request by tbrisker**
Users requiring support for Ruby 1.9 should use the fog gem

### CODE REVIEW

**Comment by ioggstream** [comment]
I'd remove Ruby 2.0 too as that doesn't support YAML.safe_load.

**Comment by tbrisker** [comment]
@ioggstream thanks, updated with dropping 2.0 as well.

**Comment by ioggstream** [comment]
@tbrisker can you reference #329 and #327 in your commit message?

**Comment by tbrisker** [comment]
@ioggstream Updated, thanks

**Comment by ioggstream** [comment]
@tbrisker reach out here for discussion https://gitter.im/fog/fog-openstack

**Comment by seanhandley** [comment]
Awesome 👍

**Pull request merged**
