### PR TITLE
Improve create server

### PR DESCRIPTION
**Pull request by scambra**
When I set port_id in nics, it fails to create, if I remove uuid from request, it works.

Also, I need some more parameters in block_device_mappings_v2: 
device_type, disk_bus, guest_format, virtual_name

### CODE REVIEW

**Comment by seanhandley** [comment]
Thanks @scambra 

Can you tell us some details about the OpenStack platform you're running this against?

i.e. Release level, Nova version etc

This code's very widely used in production so we need to understand why it works for some users and not others.

**Comment by scambra** [comment]
# nova --version
2.17.0
# dpkg -l nova-common|grep nova
ii  nova-common                          1:2014.1.5-0ubuntu1.4

**Comment by seanhandley** [comment]
I'll revisit this soon @scambra - December/January have been hard months with regard to spare time!

**Comment by guigui89** [comment]
Hello, is this pull request going to be approved and merged? I would like to use this feature for my project.

**Comment by Carthaca** [comment]
Hi, the first part lgtm.

But I don't see the device_type, disk_bus & virtual_name in the [api-ref](https://developer.openstack.org/api-ref/compute/?expanded=create-server-detail#create-server), can you point me to where these are listed as valid options, please?

**Comment by guigui89** [comment]
Hello, I would only need the first part of this pull request (commit ref: db6d424dcbbb245f7b74bb7f9159ca8a21e804d0)

**Comment by scambra** [comment]
I'm not using guest_format and virtual_name anymore, I don't remember what I was using for, but I'm still use device_type and disk_bus and they work. I found doc here for guest_format, device_type and disk_bus:

https://docs.openstack.org/developer/nova/block_device_mapping.html

If you agree, I can remove virtual_name from pull request

**Comment by scambra** [comment]
Here is doc about virtual_name, maybe it's old parameter which has been removed

**Comment by Carthaca** [comment]
`virtual_name` is legacy, it was changed 4 years ago: https://github.com/openstack/nova/commit/d581ed04a584fdd83df78e43366a3617b154a626

**Comment by Carthaca** [comment]
Thanks for bringing this up :)

**Comment by guigui89** [comment]
Thank you for the responses. When is going to be a new release date for fog-openstack?

**Pull request merged**
