### PR TITLE
Allow compute URLs ending with service version

### PR DESCRIPTION
**Pull request by beyhan**
Some OpenStack systems provide URLs like
http://host:port/v2.1 for the compute service which didn't match.
This fix changes the version regex to match such URLs

### CODE REVIEW

**Comment by voelzmo** [comment]
Seems like the travis builds failed due to a different reason than our code changes. Can we re-trigger the checks ourselves somehow?

**Comment by timuralp** [comment]
@voelzmo there should be a "Restart build" button in the top right on Travis. I re-triggered the tests.

**Comment by voelzmo** [comment]
I think 'restart build' is only there for committers. Mere contributors can't see that button.

**Comment by Carthaca** [comment]
close and re-open should work in that case

**Comment by timuralp** [comment]
@voelzmo unfortunately, you're bumping into https://github.com/fog/fog-openstack/issues/349. I submitted a PR to resolve it (#351). I also discovered that there are two more spec tests that fail when running them locally. @Carthaca do you observe failing "Reloads image state from the server" and "CRUD rbacs" tests as well?

I'll try to figure out what's happening with them :\

**Comment by timuralp** [comment]
Debugging this further, it looks like the two failing spec tests arise after upgrading to fog-core 2.0. I'm going to change the gemspec to point to `fog-core ~> 1.40` and we can tackle the upgrade to 2.0 separately.

**Comment by voelzmo** [comment]
thanks for debugging, @timuralp!

**Comment by voelzmo** [comment]
Seems like rebasing on master helped with the travis checks, thanks @timuralp

**Comment by Carthaca** [comment]
lgtm

**Pull request merged**
