### PR TITLE
examples/image/upload-test-image.rb is executable but has no shebang, removing executable bit

### PR DESCRIPTION
**Pull request by bdunne**
Found in https://github.com/ManageIQ/manageiq-rpm_build/issues/200

### CODE REVIEW

**Comment by bdunne** [comment]
Bump

**Comment by bdunne** [comment]
@geemus Do you have a minute to look at this?

**Review by geemus — APPROVED** [review]
Looks good to me, thanks for the bump/nudge (I must have missed it initially).

**Comment by bdunne** [comment]
Thank you!

**Pull request merged**
