### PR TITLE
Fix get_project request path

### PR DESCRIPTION
**Pull request by aufi**
Get project method failed on bad component(expected absolute path component),
caused by question mark in the path. Updating request to same approach as other
working requests.

### CODE REVIEW

**Comment by mansam** [comment]
It would be really great to get this merged asap once @aufi fixes the tests :)

**Comment by aufi** [comment]
@Ladas or others Hi, do you know if there are steps how to re-record VCRs? Thanks

**Comment by gildub** [comment]
@aufi, in your local environment delete ' spec/fixtures/openstack/identity_v3/idv3_project_crud.yml' file then run `bundle exec rake spec` and see the error message from VCR.

Basically the `:new_episodes` option would allow you to record a new cassette. For that you would have to add the option in the line:
```ruby
 VCR.use_cassette('authv3_a', :new_episodes)
```
Or something like that.

**Comment by gildub** [comment]
@aufi, there was no need to change VCR, the issue was some `options` still being initialized as Array.

**Comment by gildub** [comment]
@mansam, do know if there are any back port needs?

**Comment by mansam** [comment]
@gildub Not that I am aware of.

**Pull request merged**
