### PR TITLE
Filter unsupported params for volume update request

### PR DESCRIPTION
**Pull request by alexander-demichev**
Filtering unsupported params for volume update request should fix this issue https://bugzilla.redhat.com/show_bug.cgi?id=1624840

https://developer.openstack.org/api-ref/block-storage/v3/index.html#update-a-volume

@aufi @gildub

### CODE REVIEW

**Comment by gildub** [comment]
LGTM, can you please rebase?

**Comment by gildub** [comment]
@alexander-demichev, you need to filter attributes also in `save` method in following lines:
- https://github.com/fog/fog-openstack/blob/32965c7989b38c52d5d51cdf7a83de315990a26d/lib/fog/openstack/volume/v2/models/volume.rb#L20

And maybe in https://github.com/fog/fog-openstack/blob/32965c7989b38c52d5d51cdf7a83de315990a26d/lib/fog/openstack/volume/v2/models/volume.rb#L29

**Comment by gildub** [comment]
You also need to filter attributes in volume's `save` method:
- https://github.com/fog/fog-openstack/blob/32965c7989b38c52d5d51cdf7a83de315990a26d/lib/fog/openstack/volume/v2/models/volume.rb#L20

https://github.com/fog/fog-openstack/blob/32965c7989b38c52d5d51cdf7a83de315990a26d/lib/fog/openstack/volume/v2/models/volume.rb#L29

**Comment by alexander-demichev** [comment]
@gildub Hi, how can I rerecord vcrs?

**Comment by gildub** [comment]
@alexander-demichev, the information is available here https://github.com/fog/fog-openstack/blob/master/spec/shared_context.rb#L3-L18.

Basically if you have the environment setup and the fixture file is missing it will record.

Please, let me know if you're stuck.

**Comment by alexander-demichev** [comment]
Hi, @gildub 
I was trying to re-record VCRs, but I'm getting this error `"{\"error\": {\"message\": \"The request you have made requires authentication.\", \"code\": 401, \"title\": \"Unauthorized\"}}"`  here https://github.com/fog/fog-openstack/blob/master/lib/fog/openstack/auth/token.rb#L45
I put binding.pry and checked creds[:data], everything looks ok.

```
[1] pry(#<Fog::OpenStack::Auth::Token::V3>)> creds[:data]
=> {"auth"=>
  {"identity"=>{"methods"=>["password"], 
   "password"=>{:user=>{:name=>"admin", :domain=>{:name=>"Default"}, :password=>"password"}}},
   "scope"=>{:domain=>{:name=>"Default"}}}}
```

Can you take a look to this?

**Comment by gildub** [comment]
@alexander-demichev, no worries, I'm on it.

**Comment by gildub** [comment]
@alexander-demichev, I've added a commit which takes care of:
- the related fixtures: the main issue is volume v1 is obsolete and v2 is deprecated so I filtered out the extra parameters from the respective requests.
- Because of the shared structure between v1 and v2, separate behavior is needed between the 2 versions. 

If you're happy with, we can merge.

**Pull request merged**
