### PR TITLE
Add valid response codes for keypair create/delete.

### PR DESCRIPTION
**Pull request by rdgold94**
Proposed fix for #373 
Change-Id: I028e88e0dfbd8fd7a6b197bda4212b184cc719cc

### CODE REVIEW

**Comment by kjorg50** [comment]
@dhague @Ladas - could one of you take a look at this? I think it's a simple fix and our team would like to have this :)

**Comment by gildub** [comment]
@rdgold94, thanks for your help.

**Comment by rdgold94** [comment]
Hi @gildub , just out of curiosity, any idea when the next version of fog-openstack will be out so we know when this fix will be available?

**Comment by gildub** [comment]
@rdgold94, sorry for late response, a new version to be released later this week.... Thanks

**Pull request merged**
