### PR TITLE
Restoring spec tests with minitest/spec

### PR DESCRIPTION
**Pull request by gildub**
This part of an effort to consolidate unit tests and to use minitest per
fog-core project.

/spec is containing lot of tests using vcr/webmock using Rspec. This has now
been replaced Rspec with minitest. `minitest_helper.rb` file has been merged
with `spec_helper.rb`.

In the meantime all tests are merged under same umbrella. The /spec unit tests
can be executed using the added Rake task `spec`.

The `vcr` gem's cassettes path seemed inconsistent. There are now located in
/spec/fixtures/openstack.

The `turn` gem has been removed. Used for test results comestic, it's obsolete
and not maintained anymore.

All the existing tests are now passing (but 2, see below), restoring 66 tests,
409 assertions, 0 failures, 0 errors, 11 skips.

Note: There are 2 `identity_v3_spec.rb` which are on errors (not sure they were
green or not). They have been marked as skipped and commented.

### CODE REVIEW

**Comment by gildub** [comment]
@Ladas, I've tracked few hounds error, there are more mostly from legacy but the more we address now the better, let me know if you think there are other important ones. Thanks

**Comment by dhague** [comment]
@seanhandley, @mdarby, @jjasghar, @ladas & @gildub: I'd like to merge this PR so that I can then update the test changes I made in my other PRs #93 #94 #96 and #97 to be compatible with minitest. OK with you guys?

**Comment by Ladas** [comment]
@dhague I am doing the review every day, but I am always dragged by something away before I finish. :-D I'll try to review and merge soon. @mdarby would be nice to have your eyes on this :-)

**Comment by gildub** [comment]
@Ladas , thanks, that would help integrate @dhague work with all the VCR effort as well as #93 fixes around keytsone v3.

**Comment by mdarby** [comment]
I'm missing the context of this shift (Fog is moving away from shindo to minitest?) If so, all the better.

**Comment by Ladas** [comment]
Alright, seems to me mostly rspec to minitest syntax change. Looks good to me in overall, I am ready to merge sice this blocks other PRs. :+1:  We can fix more hound errors later, otherwise @gildub would have to rewrite all of our code in one PR. :-)

**Pull request merged**
