### PR TITLE
Update token.rb

### PR DESCRIPTION
**Pull request by badde-media**
Trying to fix this error (https://github.com/fog/fog-openstack/issues/535) by changing the input to_s before trying to match it with the regex

### CODE REVIEW

**Comment by badde-media** [comment]
Using my fixed version, this bug is actually gone, but I still get an auth error

**Comment by geemus** [comment]
@badde-media progress at least, as you said. Could you share what your credentials look like (please be sure to sanitize them by putting in placeholder values for any secrets) and the details of the new error you are now seeing? Thanks.

**Comment by badde-media** [comment]
Hello again, sorry for the late reply. I was getting crazy with some other problems this app had. 

This is the storage.yml I've used that finally worked with Infomaniak S3 Object Storage:
```
infomaniak:
   service: S3
   access_key_id: <%= Rails.application.credentials.dig(:infomaniak, :access_key_id) %>
   secret_access_key: <%= Rails.application.credentials.dig(:infomaniak, :secret_access_key) %>
   region: "us-east-1"
   bucket: "myBucketName"
   endpoint: "https://s3.pub1.infomaniak.cloud"
   public: true
```   
using the version of this gem that I had patched. So I didn't even have to enter the version.
Here's another version that also could connect, as far as I can remember:
```
 openstack:
     auth:
       auth_url: https://api.pub1.infomaniak.cloud/identity
       username: "username"
       project_id: project_id
       project_name: "project_name"
       user_domain_name: "Default"
     region_name: "dc3-a"
     interface: "public"
     identity_api_version: 3
```
In this case, the identity_api_version only worked when entered like this, just as an Integer. no "v3" or something like that.

BUT one of the aforementioned problems is that Infomaniak S3 DOES NOT SUPPORT CORS, wich renders this service useless for live-streaming via HTTPS directly from the object storage, and also for direct uploads as ActiveStorage offers it. I guess that Infomaniak want to sell their more expensive audio- and video-streaming servers for this purpose. 
This has nothing to do with fog-openstack, but I'm mentioning it just in case that others run into the same problems that I have had, and where you can hardly find any information online. Because of this CORS error, we're now switching most probably to DigitalOcean. This is my DO storage.yml entry that also works using my patched version:
```
digitalocean:
  service: S3
  endpoint: https://fra1.digitaloceanspaces.com
  access_key_id: <%= Rails.application.credentials.dig(:digitalocean, :access_key) %>
  secret_access_key: <%= Rails.application.credentials.dig(:digitalocean, :secret) %>
  bucket: myBucketName
  region: unused
```
(nb: do not enter the bucket name in the endpoint url)
This also just for completeness.

I guess we can close this commit, no?

**Comment by geemus** [comment]
Thanks for the update, sure I will close for now.

**Pull request closed without merging**
